### ISSUE TITLE
Add awsebcli?

### ISSUE THREAD

**Issue by felicianotech** [cibuilds/aws#106]

**Comment by TimonVS** [comment]
It would be great if EB CLI could be included :)

**Comment by felicianotech** [comment]
If I get this included, can you help me test it to make sure it works? I don't use EB myself.

**Comment by TimonVS** [comment]
Sure! It would save me a bunch of time creating my own Docker image and keeping it up-to-date :)

**Comment by felicianotech** [comment]
Cool. I'll get it into the image for the AWS CLI 1.16.152. I'll ping you here when it's ready for you to test. Thanks.

**Comment by felicianotech** [comment]
Hey @TimonVS, can you test the `cibuilds/aws:1.16.153` image to see if the eb cli is working right for you?

**Comment by TimonVS** [comment]
Works perfectly fine over here 🎉

**Comment by felicianotech** [comment]
Awesome. I'll consider this issue completed then. Thank you for testing for me.
