### ISSUE TITLE
latest tag is changing between major versions - new tags?

### ISSUE THREAD

**Issue by MartinP-C** [cibuilds/aws#576]
Could new tags be implemented for latest release for each major version?

I updated all CI scripts to use `sudo apt-get` on v2 instead of `apk add` when `latest` became v2.
Now the `latest` is a v1 release and CI jobs fail.

So that I can use the latest release of v2 when they are published, can new tags be implemented for latest v1 and latest v2?

**Comment by felicianotech** [comment]
Great point. I don't know if I'll do one for v1, but I'll make `latest` only point to v2 of the CLI starting with the next v2 release.

**Comment by MartinP-C** [comment]
All builds back to normal.
Thanks!
